// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://admnccestkktegtjwxng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkbW5jY2VzdGtrdGVndGp3eG5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MDUzMzMsImV4cCI6MjA2ODQ4MTMzM30.CoG3R3X381WS_YA2NQ5lZV-3ls645pl2aX2AUeusM98";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});